config/routes.rb
Csv2sql::Application.routes.draw do
  
  resources :questions do
    resources :options
  end

  get "charts/index"

  root :to => 'files#index'
  
  match '/upload' => 'files#upload',as: :upload
  match '/result' => 'files#result',as: :result
  match '/reset(/:o_id)' => 'files#reset',as: :reset
  match '/reset_files' => 'files#reset_files',as: :reset_files
  match '/charts(/questions/:question_id(/:chart_type))' => 'charts#index',as: :chart
  match '/charts/series/:series_type(/questions/:question_id(/:chart_type))' => 'charts#series',as: :chart_series
  
  match '/check_ids' => 'files#check_ids', as: :check_id
  
  match '/get_options' => 'charts#get_options'
  match '/add_series' => 'charts#add_series'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question, :multi_check
  
  has_many :options,dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question,html: {class: "form-horizontal"}) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :question, class: "control-label" %>
	<div class="controls">
    	<%= f.text_field :question %>
	</div>
  </div>

  <div class="control-group">
  	<div class="controls">
  		<%= f.check_box :multi_check %> Allow Multi-checked
  	</div>
  </div>
  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="page-header">
<h1>Editing question</h1>
</div>
<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="page-header">
<h1>Manage Questions</h1>
</div>


<table class="table">
  <tr>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.question %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<div class="page-header">
<h1>New question</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<% if notice  %>
<div class="alert alert-info" id="notice"><%= notice %></div>
<% end  %>

<div class="page-header">
  <h1>Question <%= @question.id %>:
  <%= @question.question %></h1>
</div>

<% if !@question.options.blank? %>
<ul class="unstyled">
  <% for option in @question.options.order("option_id") %>
    <li><%= option.option %> (<%= option.option_id %>) <%= link_to "Edit Option",edit_question_option_path(@question,option) %></li>
  <% end %>
</ul>
<% else %>
  
<% end %>


<%= link_to 'Add Options',new_question_option_path(@question),class: "btn btn-success" %>
<%= link_to 'Edit Question', edit_question_path(@question),class: "btn btn-primary" %> 
<%= link_to 'Back to questions list', questions_path %>