config/routes.rb
Csv2sql::Application.routes.draw do
  
  resources :questions do
    resources :options
  end

  get "charts/index"

  root :to => 'files#index'
  
  match '/upload' => 'files#upload',as: :upload
  match '/result' => 'files#result',as: :result
  match '/reset(/:o_id)' => 'files#reset',as: :reset
  match '/reset_files' => 'files#reset_files',as: :reset_files
  match '/charts(/questions/:question_id(/:chart_type))' => 'charts#index',as: :chart
  match '/charts/series/:series_type(/questions/:question_id(/:chart_type))' => 'charts#series',as: :chart_series
  
  match '/check_ids' => 'files#check_ids', as: :check_id
  
  match '/get_options' => 'charts#get_options'
  match '/add_series' => 'charts#add_series'

end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
  attr_accessible :option,:option_id
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  # GET /options
  # GET /options.json
  before_filter :get_question
  
  def index
    @options = @question.options.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = @question.options.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = @question.options.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = @question.options.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = @question.options.build(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to question_path(@question), notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = @question.options.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to question_path(@question), notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = @question.options.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to question_path(@question) }
      format.json { head :no_content }
    end
  end
  
  private
  
  def get_question
    @question = Question.find(params[:question_id]) if params[:question_id]
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_for [@question,@option],html: {class: "form-horizontal"} do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :option, class: "control-label" %>
	<div class="control">
		<%= f.text_field :option %>
	</div>
  </div>
  <div class="control-group">
  	<%= f.label :option_id, "Option Id",class: "control-label" %>
	<div class="control">
		<%= f.text_field :option_id %>
	</div>
  </div>
  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', [@question,@option] %> |
<%= link_to 'Back', question_path(@question) %>

app/views/options/index.html.erb
<div class="page-header">
<h1>Listing options</h1>
</div>


<table class="table">
  <tr>
    <th>Option</th>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @options.each do |option| %>
  <tr>
	<td><%= option.question.question %></td>
    <td><%= option.option %></td>
    
    <td><%= link_to 'Show', [option.question,option] %></td>
    <td><%= link_to 'Edit', edit_question_option_path(@question,option) %></td>
    <td><%= link_to 'Destroy', [option.question,option], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<div class="page-header">
<h1><%= @question.question %>'s New option</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', question_path(@question) %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Option:</b>
  <%= @option.option %>
</p>

<p>
  <b>Question:</b>
  <%= @option.question %>
</p>


<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>