config/routes.rb
Csv2sql::Application.routes.draw do
  
  resources :questions do
    resources :options
  end

  get "charts/index"

  root :to => 'files#index'
  
  match '/upload' => 'files#upload',as: :upload
  match '/result' => 'files#result',as: :result
  match '/reset(/:o_id)' => 'files#reset',as: :reset
  match '/reset_files' => 'files#reset_files',as: :reset_files
  match '/charts(/questions/:question_id(/:chart_type))' => 'charts#index',as: :chart
  match '/charts/series/:series_type(/questions/:question_id(/:chart_type))' => 'charts#series',as: :chart_series
  
  match '/check_ids' => 'files#check_ids', as: :check_id
  
  match '/get_options' => 'charts#get_options'
  match '/add_series' => 'charts#add_series'

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  
  
  def index
    if params[:question_id]
      id = params[:question_id]
      @question = Question.find(id)
      @answers = Hash[get_answers(@question)]
     
    end
  end
  
  def series
    @series_type = params[:series_type]
    @need_percent = params[:need_percent]
    case @series_type
    when "life"
      @questions = Question.where(id: [1,2,3,4,5,7,9,10,11,12,13,14,15,16,17])
      @series = Question.where(id: [1,2,3,4,5,6,8])
    when "work"
      @questions = Question.where(id: [18,20,21,22,23,24,25,26])
      @series = Question.where(id: [1,2,3,4,5,6,19])
    when "venture"
      @questions = Question.where(id: [27,28,29,30,31,32,33,34,35,36])
      @series = Question.where(id: [1,2,3,4,5,6,19])
    end
    
    
    if params[:series_question]
      @has_series = true
      
       #show series
        @question = Question.find(params[:original_question])
        @s_options = params[:option]

        
        @chart_option = []
        
        
        @s_options.each do |s_option|
          @s = Hash.new
          @s["name"] = Option.find_by_option_id(s_option.first).option  # for series name
          @s["data"] = get_answers(@question,s_option.first).to_a  #get etc. "0302" option as series
          
          @chart_option << @s
          
        end
        
        #@s:{"name"=>"2 个", "data"=>{"1001"=>395, ..."1002"=>581}}
        #@chart_option:[{"name"=>"option1", "data"=>[1, 2, 3]}, {"name"=>"option2", "data"=>[1, 2, 3]}] 
        
        
    elsif params[:question_id]
      @has_series = false
      #show total
      id = params[:question_id]
      @question = Question.find(id)
      @answers = Hash[get_answers(@question)]
    else
      @has_series = nil
    end
    
  end
  
  def get_options
    @options = Question.find(params[:series_question_id]).options
    render :partial => "options", :object => @options,locals: {series_question_id: params[:series_question_id],original_question_id: params[:original_question_id],series_type: params[:series_type]}
  end
  
  
  def get_total_answer_with_special_options(question,s_option_id) 
    #initialize
    table_question = find_table_question(question)
    table_option = find_table_option(s_option_id)
    total_answer_option_count = 0
    
    
    question.options.each do |option|
      answers_with_option = get_option_count(table_question,table_option,option,s_option_id)
    
      #means:  T_1.joins("inner join t_2s on t_1s.o_id = t_2s.o_id").where("t_1s.o_0101 = ? and t_2s.o_0802 = ?",true,true).count
      total_answer_option_count += answers_with_option
    end
    
    return total_answer_option_count
  end
  
  def find_table_option(s_option_id)
    
        table_option = ""
         if "01,02,03,04,05,06".include? s_option_id[0,2]
           table_option = "T_1"
         elsif "07,08,09,10,11,12,13,14,15,16,17".include? s_option_id[0,2]
           table_option = "T_2"
         elsif "18,19,20,21,22,23,24,25,26,27".include? s_option_id[0,2]
           table_option = "T_3"
         elsif "28,29,30,31,32,33,34,35,36".include? s_option_id[0,2]
           table_option = "T_4"
         end
      
      return table_option
  end
  
  def find_table_question(question)
    table_question = ""
    case question.id
    when 1..6 
     table_question = "T_1"
    when 7..17 
     table_question = "T_2"
    when 18..26 
     table_question = "T_3"
    when 27..36 
     table_question = "T_4"
    end
    return table_question
  end
  
  def  get_answers(question,s_option_id=nil,need_percent=@need_percent)
    answers = Hash.new
    
    
    #if has another options to add series
     table_option = find_table_option(s_option_id)  if s_option_id
       
    
    #question.id means which table the question's options are
    #s_option_id means which table the additional series options are
    #so we should query the data joins 2 different tables or 1 same table.
    table_question = find_table_question(question)
    
    answer_option_count = get_total_answer_with_special_options(question,s_option_id) if s_option_id   #initial the count of total answers with special addtional option
    
    question.options.each do |option|
      
      if s_option_id
        answers_with_option = get_option_count(table_question,table_option,option,s_option_id)  #get the option count
        
        if need_percent  #use the data of percent (%)
          answers[option.option_id] = (answers_with_option.to_f/answer_option_count.to_f*100).round(2)    #got percent
        else
          answers[option.option_id] = answers_with_option.to_f.round(2)  #got absolute number
        end
      else
        
        answers[option.option_id]  = eval "#{table_question}.where('o_#{option.option_id} = ?',true).count"
      end
    end
     
    return answers.to_a
  end
  
  
  def get_option_count(table_question,table_option,option,s_option_id)
    if table_question == table_option
      answers_with_option = eval "#{table_question}.where('#{table_question.downcase.pluralize}.o_#{option.option_id} = ? and #{table_option.downcase.pluralize}.o_#{s_option_id} = ?',true,true).count" #count of this option with addtional option
      
    else
      answers_with_option = eval "#{table_question}.joins('inner join #{table_option.downcase.pluralize} on #{table_question.downcase.pluralize}.o_id = #{table_option.downcase.pluralize}.o_id').where('#{table_question.downcase.pluralize}.o_#{option.option_id} = ? and #{table_option.downcase.pluralize}.o_#{s_option_id} = ?',true,true).count" 
    
    #means:  T_1.joins("inner join t_2s on t_1s.o_id = t_2s.o_id").where("t_1s.o_0101 = ? and t_2s.o_0802 = ?",true,true).count
    end
    return answers_with_option
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_options.html.erb
<%# debugger %>
<%= form_tag("/charts/series/#{series_type}/questions/#{original_question_id}",method: :get) do %>
<%= hidden_field_tag "series_question",series_question_id  %>
<%= hidden_field_tag "original_question",original_question_id %>
<% @options.each do |option| %>
<label class="checkbox inline">
	<%= check_box_tag "option[#{option.option_id}]" %> <%= option.option %>
</label>
<% end %>

<%= submit_tag "Refresh Chart",class: "btn btn-primary pull-right" %>

<% end %>

app/views/charts/index.html.erb
<div class="page-header">
	<h1>Charts</h1>
	
</div>



<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">Single Analysis</a>
  </li>
  <li><a href="/charts/series/life"><i class="icon-shopping-cart"></i>About Life</a></li>
<li><a href="/charts/series/work"><i class="icon-bookmark"></i>About Work</a></li>
<li><a href="/charts/series/venture"><i class="icon-cog"></i>About Venture & Development</a></li>
</ul>



<%= select_tag "question", options_from_collection_for_select(Question.all, "id", "question"), :prompt => "Select a question" %>

<script>
	$(document).ready(function () 
	{
	    $("#question").change(function(){
	        location.href="/charts/questions/"+this.options[this.selectedIndex].value;
	    });
	});
</script>

<% if @question %>
	<h2>
		<%= @question.question %>
	</h2>

	<% if !@question.options.blank? %>
		<!--chart-->
		<div class="span12">
			<%= link_to chart_path(@question,"column"),class: "btn btn-success" do %>
				<i class="icon-white icon-signal"></i> Column
			<% end %>
			<%= link_to chart_path(@question,"pie"),class: "btn btn-success" do %>
				<i class="icon-white icon-th-large"></i> Pie
			<% end %>
		</div>
		<div id="container" class="span12" style="height: 400px"></div>
		
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<% for option in @question.options %>
				<tr>
					<th>
						<%= option.option %>
					</th>
					<td>
						<%= @answers[option.option_id] %>
					</td>
				</tr>
			    
			  <% end %>
			</tbody>
		</table>
	  

	


	<script>
		var chart_type = '<%= params[:chart_type]||="pie" %>'; //default is pie
		$(document).ready(function() {
		      chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container',
						type: chart_type
					},
					title: {
						text: '<%= @question.question %>'
					},
					<% if params[:chart_type]=="pie" %>
						plotOptions: {
									pie: {
										allowPointSelect: true,
										cursor: 'pointer',
										dataLabels: {
											enabled: true,
											color: '#000000',
											connectorColor: '#000000',
											formatter: function() {
												return '<b>'+ this.point.name +'</b>: '+ Highcharts.numberFormat(this.percentage, 1) +' %';
											}
										}
									}
								},
								series: [{
											type: 'pie',
											<% 
												data = Hash.new
												@question.options.each do |option| 
													data[option.option]=@answers[option.option_id]
												end
											%>
											data: <%= raw data.to_a %>
										}]
					<% else %>
						xAxis: {
										<% 
												category = []
												@question.options.each do |option| 
													category << option.option
												end
										%>
							categories: <%= raw category.to_a %>,
							labels: {
											rotation: -20,
											align: 'right',
											style: {
												font: 'normal 13px Verdana, sans-serif'
											}
										}
						},
						yAxis: {
							min: 0,
							title: {
								text: 'Numbers'
							}
						},
						
						series: [{
									type: 'column',
									name: 'total',
									<% 
										data = []
										@question.options.each do |option| 
											data << @answers[option.option_id]
										end
									%>
									data: <%= raw data.to_a %>
								}]
					<% end %>
					
				});
		   });
	</script>
	<% else %>
  
	<% end %>
<% end %>

app/views/charts/life.html.erb
<div class="page-header">
	<h1>Charts</h1>
	
</div>



<ul class="nav nav-tabs">
  <li>
    <a href="/charts">Single Analysis</a>
  </li>
  <li  class="active"><a href="#"><i class="icon-shopping-cart"></i>About Life</a></li>
<li><a href="#"><i class="icon-bookmark"></i>About Work</a></li>
<li><a href="#"><i class="icon-cog"></i>About Venture & Development</a></li>
</ul>

<!--questions-->
	<div class="row">
		<div class="span4">

			<%= select_tag "question", options_from_collection_for_select(@questions, "id", "question"), :prompt => "Select a question" %>

			<script>
				$(document).ready(function () 
				{
				    $("#question").change(function(){
				        location.href="/charts/life/questions/"+this.options[this.selectedIndex].value;
				    });
				});
			</script>
		</div>
		<div class="span4">	
			<% if @question %>
			<!--options-->
			<a href="#" onClick="$('#more_option').slideToggle();" class="btn btn-info"><i class="icon-plus-sign"></i> Add More Series...</a>
			<% end %>
		</div>
	</div>

<% if @question %>
	

	<% if !@question.options.blank? %>
		
		<div id="more_option" style="display:none" class="well">
			<%= select_tag "series", options_from_collection_for_select(@series, "id", "question"), :prompt => "Select a series",onchange: "showOption(this.value,#{@question.id});" %>
			
			<!--checkbox for more option-->
			<div id="more_series"></div>
		</div>

		<!--chart-->
		<div class="row">
			<div id="container" class="span12" style="height: 400px"></div>
		</div>
		
		<% unless @has_series %>
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<% for option in @question.options %>
				<tr>
					<th>
						<%= option.option %>
					</th>
					<td>
						<%= @answers[option.option_id] %>
					</td>
				</tr>
			    
			  <% end %>
			</tbody>
		</table>
	  <% end %>

	<script>
		var chart_type = '<%= params[:chart_type]||="column" %>'; //default is pie
		$(document).ready(function() {
		      chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container',
						type: chart_type
					},
					title: {
						text: '<%= @question.question %>'
					},
					
						xAxis: {
										<% 
												category = []
												@question.options.each do |option| 
													category << option.option
												end
										%>
							categories: <%= raw category.to_a %>,
							labels: {
											rotation: -20,
											align: 'right',
											style: {
												font: 'normal 13px Verdana, sans-serif'
											}
										}
						},
						yAxis: {
							min: 0,
							title: {
								text: 'Numbers'
							}
						},
						
						series: 
									<% if @chart_option %>
									<%= raw	@chart_option.to_json
									%>
									
									<% else %>
									[{
										name: 'Total',
										<% 
											data = []
											@question.options.order('id').each do |option| 
												data << @answers[option.option_id]
											end
										%>
										data: <%= raw data.to_a %>
									}]
									<% end %>
								
					
				});
		   });
	</script>
	<% end %>
<% end %>

app/views/charts/series.html.erb
<div class="page-header">
	<h1>Charts</h1>
	
</div>



<ul class="nav nav-tabs">
  <li>
    <a href="/charts">Single Analysis</a>
  </li>
  <li <%= "class='active'" if @series_type=="life" %>><a href="<%= chart_series_path(series_type: "life") %>"><i class="icon-shopping-cart"></i>About Life</a></li>
<li <%= "class='active'" if @series_type=="work" %>><a href="<%= chart_series_path(series_type: "work") %>"><i class="icon-bookmark"></i>About Work</a></li>
<li <%= "class='active'" if @series_type=="venture" %>><a href="<%= chart_series_path(series_type: "venture") %>"><i class="icon-cog"></i>About Venture & Development</a></li>
</ul>

<!--questions-->
	<div class="row">
		<div class="span4">

			<%= select_tag "question", options_from_collection_for_select(@questions, "id", "question"), :prompt => "Select a question" %>

			<script>
				$(document).ready(function () 
				{
				    $("#question").change(function(){
				        location.href="/charts/series/<%= params[:series_type] %>/questions/"+this.options[this.selectedIndex].value;
				    });
				});
			</script>
		</div>
		<div class="span4">	
			<% if @question %>
			<!--options-->
			<a href="#" onClick="$('#more_option').slideToggle();" class="btn btn-info"><i class="icon-plus-sign"></i> Add More Series...</a>
			<% end %>
		</div>
	</div>

<% if @question %>
	

	<% if !@question.options.blank? %>
		
		<div id="more_option" style="display:none" class="well">
			<%= select_tag "series", options_from_collection_for_select(@series, "id", "question"), :prompt => "Select a series",onchange: "showOption(this.value,#{@question.id},'#{@series_type}');" %>
			
			<!--checkbox for more option-->
			<div id="more_series"></div>
		</div>

		<!--chart-->
		<div class="row">
			<div id="container" class="span12" style="height: 400px"></div>
		</div>
		
		<% unless @has_series %>
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<% for option in @question.options %>
				<tr>
					<th>
						<%= option.option %>
					</th>
					<td>
						<%= @answers[option.option_id] %>
					</td>
				</tr>
			    
			  <% end %>
			</tbody>
		</table>
	  <% end %>

	<script>
		var chart_type = '<%= params[:chart_type]||="spline" %>'; //default is spline
		$(document).ready(function() {
		      chart = new Highcharts.Chart({
					chart: {
						renderTo: 'container',
						type: chart_type
					},
					title: {
						text: '<%= @question.question %>'
					},
					
						xAxis: {
										<% 
												category = []
												@question.options.each do |option| 
													category << option.option
												end
										%>
							categories: <%= raw category.to_a %>,
							labels: {
											rotation: -20,
											align: 'right',
											style: {
												font: 'normal 13px Verdana, sans-serif'
											}
										}
						},
						yAxis: {
							min: 0,
							title: {
								text: 'Numbers'
							}
						},
						plotOptions: {
									spline: {
										dataLabels: {
											enabled: true
										},
										enableMouseTracking: true
									},
									column: {
										dataLabels:{
											enabled: true
										}
									}
								},
						series: 
									<% if @chart_option %>
										<%= raw	@chart_option.to_json
									%>
									
									<% else %>
									[{
										name: 'Total',
										<% 
											data = []
											@question.options.order('id').each do |option| 
												data << @answers[option.option_id]
											end
										%>
										data: <%= raw data.to_a %>
									}]
									<% end %>
								
					
				});
		   });
	</script>
	<% end %>
<% end %>

<!-- percent or number -->
<% if @has_series %>
	<% if params[:need_percent] %> 
		Now it is using PERCENT (%),
		<%= link_to "Show Number",request.url.sub(/&need_percent=true/,''),class: "btn" %>
	<% else %>
		Now it is using NUMBERS,
		<%= link_to "Show Percent(%)",request.url+"&need_percent=true",class: "btn" %>
	<% end %>

	<% if params[:chart_type] == "column" %>
		<%= link_to "Use Spline", request.url+"&chart_type=spline",class: "btn btn-primary" %>
	<% else %>
		<%= link_to "User Column",request.url+"&chart_type=column",class: "btn btn-primary" %>
	<% end %>
<% end %>