config/routes.rb
Csv2sql::Application.routes.draw do
  
  resources :questions do
    resources :options
  end

  get "charts/index"

  root :to => 'files#index'
  
  match '/upload' => 'files#upload',as: :upload
  match '/result' => 'files#result',as: :result
  match '/reset(/:o_id)' => 'files#reset',as: :reset
  match '/reset_files' => 'files#reset_files',as: :reset_files
  match '/charts(/questions/:question_id(/:chart_type))' => 'charts#index',as: :chart
  match '/charts/series/:series_type(/questions/:question_id(/:chart_type))' => 'charts#series',as: :chart_series
  
  match '/check_ids' => 'files#check_ids', as: :check_id
  
  match '/get_options' => 'charts#get_options'
  match '/add_series' => 'charts#add_series'

end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  require 'uuidtools'
  require 'csv'
  
  def index
    @records_counter = T_1.all.count
    @last_id = T_1.last.o_id unless @records_counter == 0
    
    @dir = Dir.open("#{Rails.root}/public/upload")
  end
  
  def upload
    if @filename=uploadFile(params[:file],params[:file_type])
      #debugger
      @result = parsing(@filename)
      flash[:msg] = "file parsed!"
      redirect_to root_path
    else
      flash[:error] = "file upload failed!"
      redirect_to root_path
    end
  end
  
  def reset
    if params[:o_id]
      T_1.find_by_o_id(params[:o_id]).destroy
      T_2.find_by_o_id(params[:o_id]).destroy
      T_3.find_by_o_id(params[:o_id]).destroy
      T_4.find_by_o_id(params[:o_id]).destroy
    else
      T_1.delete_all
      T_2.delete_all
      T_3.delete_all
      T_4.delete_all
    end
    
    flash[:msg] = "All the data are deleted."
    redirect_to root_path
  end
  
  def reset_files
    Dir["#{Rails.root}/public/upload/*"].each {|f| File.delete(f)}  #delete all the file uploaded
    flash[:msg] = "All the files are deleted."
    redirect_to root_path
  end
  
  def check_ids
    records_count = T_1.all.size
    
    @absent = []
    (1..records_count).each do |current_id|
      
      unless T_1.find_by_o_id(current_id)
        
        @absent << current_id 
      end
    end
    
  end


private
  def uploadFile(file,file_type)    
       if !file.original_filename.empty?  
         #生成一个随机的文件名      
         
         #debugger
         
         if file_type == "csv"
           newfilename = UUIDTools::UUID.timestamp_create().to_s+'.csv'
         elsif file_type == "xls"
           newfilename = UUIDTools::UUID.timestamp_create().to_s+'.xls'
         end
         
         #向dir目录写入文件  
         #debugger
         File.open("#{Rails.root}/public/upload/#{newfilename}", "wb") do |f|   
            f.write(file.read)  
         end   
         
         #debugger
         #返回文件名称，
         return newfilename  
       end  
    end
    
    def parsing(filename)
      
      
      file_type = filename.slice(-3,3)
      
      if file_type == "csv"
        parse_csv(filename)
      else
         parse_xls(filename)
      end
    end
     
     def parse_csv(file)
       File.readlines("#{Rails.root}/public/upload/#{file}").each do |line|  

            current_row = line.chomp.split(',')
              
            (2..current_row.size-1).each do |i|
              unless current_row[i]==""
               question = current_row[i][0,2]  # got the question number
               #answer = current_row[i][2,2]    # got the answer number
               
               #select the table
                 if "01,02,03,04,05,06".include? question
                   record = T_1.find_or_create_by_o_id(current_row[0])
                 elsif "07,08,09,10,11,12,13,14,15,16,17".include? question
                   record = T_2.find_or_create_by_o_id(current_row[0])
                 elsif "18,19,20,21,22,23,24,25,26,27".include? question
                   record = T_3.find_or_create_by_o_id(current_row[0])
                 elsif "28,29,30,31,32,33,34,35,36".include? question
                   record = T_4.find_or_create_by_o_id(current_row[0])
                 else
                   next
                 end
                #debugger
                unless eval "record.o_#{current_row[i]} ==  true"
                 eval "record.o_#{current_row[i]} = true"  #set the answer to correct field
                 record.area = current_row[1]
                 record.save
                end
              end
            end
           
            #end of each current_row
       end
        #end of all the line
     end

     def parse_xls(file)
       
       topline = []
       
       File.readlines("#{Rails.root}/public/upload/#{file}").each do |line| 
         
         current_row = line.chomp.split(',')
         
         if current_row[0]=="o_id"  #get the field 
           topline = current_row 
         else
           
           (2..current_row.size-1).each do |i|
              question = topline[i][0,2]  # got the question number
              #select the table
                 if "01,02,03,04,05,06".include? question
                   record = T_1.find_or_create_by_o_id(current_row[0])
                 elsif "07,08,09,10,11,12,13,14,15,16,17".include? question
                   record = T_2.find_or_create_by_o_id(current_row[0])
                 elsif "18,19,20,21,22,23,24,25,26,27".include? question
                   record = T_3.find_or_create_by_o_id(current_row[0])
                 elsif "28,29,30,31,32,33,34,35,36".include? question
                   record = T_4.find_or_create_by_o_id(current_row[0])
                 end
              
                 eval "record.o_#{topline[i]} = true" if current_row[i]=="TRUE" #set the answer to correct field
                 record.area = current_row[1]
                 record.save
           end
         end
       end
     end
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/files/check_ids.html.erb
	<% if !@absent.blank? %>
	<h1>We lost <%= @absent.size %> records.</h1>
	<ul>
	
	  <% for a in @absent %>
	    <li><%= a.to_s %></li>
	  <% end %>
		
	</ul>
	<% else %>
	  <h1>
	  	No absent!
	  </h1>
	<% end %>
	

app/views/files/index.html.erb
<div class="row">
	<div class="span10">
		
		
		<% if flash[:error] %>
		<div class="alert alert-error">
			<%= flash[:error] %>
		</div>
		<% end %>


		<% if flash[:msg] %>
		<div class="alert alert-info">
			<%= flash[:msg] %>
		</div>
		<% end %>
		
		<!--header-->
		
		<div class="hero-unit center">
			<h1>
				Now we have <%= @records_counter %> records!
			</h1>
		</div>
		
		
		
	</div>

</div>

<div class="row">
	<div class="tabbable span10">
		<ul class="nav nav-tabs">
		    <li class="active"><a href="#tab1" data-toggle="tab"><i class="icon-arrow-up"></i> Upload File</a></li>
		    <li><a href="#tab2" data-toggle="tab"><i class="icon-th-list"></i> Files List</a></li>
		</ul>
		<div class="tab-content">
		    <div class="tab-pane active" id="tab1">
					<div class="">
						<!--file upload-->
						<div class="page-header">
							<small>if you have csv or excel file</small>
							<h1>Upload CSV/Excel File</h1>
						</div>

						<%= form_tag '/upload', class: "well",multipart: true do %>
						  <label for="file">File to Upload</label> <%= file_field_tag "file" %>
						  <%= select_tag "file_type", "<option value='csv'>From Excel</option><option value='xls'>From Access</option>".html_safe%>
						
						  <%= submit_tag "Upload",class: "btn btn-primary"  %>
						<% end %>
					</div>
					
				
			</div>
			<div class="tab-pane" id="tab2">
			<!--file list-->
				<div class="">
					<h1>Files Uploaded:</h1>
					<table class="table table-condensed ">
					  	<% @dir.each do |f| %>
							<% unless f=="." or f==".." %>
								<tr><td><%= link_to f,"/upload/#{f}"  %></td></tr>
							<% end %>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="span3">
		
			<!--delete data-->
			<div class="btn-group">
			  <button class="btn">
				<!--reset all the data-->
			  	<%= link_to "Reset All Data",reset_path,confirm: "This will delete all the data in database." %>
			  </button>
			  <button class="btn dropdown-toggle" data-toggle="dropdown">
			    <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu">
				<li>
					<%#= link_to "Delete Last Record: " + @last_id.to_s,reset_path(@last_id),confirm: "This will delete 1 data which id is #{@last_id} in database." unless @last_id %>
					<!--delete files-->
					<%= link_to "Clear All Uploaded Files", reset_files_path,confirm: "This will delete all the uploaded files" %>
				</li>
			  </ul>
			</div>
	
	</div>
	<div class="span6">	
				
		
			<%= link_to check_id_path,class: "btn" do %>
				<i class="icon-check"></i> Check IDs
			<% end %>
			<%= link_to chart_path,class: "btn btn-success" do %>
				<i class="icon-white icon-signal"></i> View Charts
			<% end %>
			<%= link_to questions_path,class: "btn btn-success" do %>
				<i class="icon-white icon-wrench"></i> Manage the Questions & Options
			<% end  %>
	</div>
	</div>
</div>

app/views/files/result.html.erb
<h1>
	 Parsing the result
</h1>

<div class="alert alert-success">
	Everything is OK
</div>


<a href="/">Return</a>